export const VERSION='0.2.0';
export const PROVINCES=[['京师',72,18,'ming',5],['山西',50,29,'ming',2],['山东',84,34,'ming',2],['陕西',34,42,'ming',2],['河南',59,45,'ming',1],['四川',31,60,'ming',2],['湖广',52,61,'ming',1],['江南',76,57,'ming',2],['安徽',68,52,'ming',1],['湖南',50,72,'ming',1],['江西',63,72,'ming',1],['浙江',80,72,'ming',2],['福建',82,84,'ming',2],['广东',67,88,'ming',2]].map((p,i)=>({id:['beijing','shanxi','shandong','shaanxi','henan','sichuan','hubei','jiangsu','anhui','hunan','jiangxi','zhejiang','fujian','guangdong'][i],name:p[0],x:p[1],y:p[2],owner:p[3],fort:p[4]}));
export const COUNTRIES={ming:{name:'大明',color:'#a33a32',money:100,food:500,manpower:280000,stability:62,warSupport:55,corruption:70,army:180000,cavalry:25000,focuses:{}},shun:{name:'大顺',color:'#7d3042',money:45,food:360,manpower:360000,stability:48,warSupport:72,corruption:35,army:130000,cavalry:12000,focuses:{}},qing:{name:'后金',color:'#285b6b',money:70,food:320,manpower:190000,stability:78,warSupport:80,corruption:18,army:150000,cavalry:65000,focuses:{}}};
const clone=v=>JSON.parse(JSON.stringify(v));
export function createInitialState(player='ming'){return{date:'1643-01-01',player,turn:0,countries:clone(COUNTRIES),provinces:clone(PROVINCES),selected:'beijing',log:['1643年：山河风雨欲来。']};}
export function advanceDay(state){const s=clone(state),d=new Date(s.date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1);s.date=d.toISOString().slice(0,10);s.turn++;Object.values(s.countries).forEach(c=>{c.money+=Math.max(1,Math.floor(c.army/30000));c.food-=Math.max(1,Math.ceil(c.army/100000));c.stability=Math.max(0,Math.min(100,Math.round((c.stability+(c.corruption>60?-0.08:0.03))*100)/100));});if(s.turn%30===0)ai(s);return s;}
function ai(s){const m=s.countries.ming;for(const id of ['shaanxi','shanxi','henan']){const p=s.provinces.find(x=>x.id===id);if(p&&p.owner==='ming'&&s.countries.shun.army>m.army*.55){p.owner='shun';m.army=Math.floor(m.army*.85);s.countries.shun.army=Math.floor(s.countries.shun.army*.92);s.log.unshift('大顺发动北伐，战线发生变化。');break;}}}
export function attackProvince(state,id){const s=clone(state),p=s.provinces.find(x=>x.id===id),a=s.countries[s.player];if(!p||p.owner===s.player||a.army<20000)return s;const d=s.countries[p.owner],ap=a.army*(a.stability/100)*(1+a.cavalry/a.army*.45),dp=d.army*(d.stability/100)*(1+p.fort*.08);if(ap>dp*.95){p.owner=s.player;a.army=Math.floor(a.army*.92);d.army=Math.floor(d.army*.85);s.log.unshift(`${a.name}夺取${p.name}。`);}else{a.army=Math.floor(a.army*.76);s.log.unshift(`${a.name}进攻${p.name}失败。`);}return s;}
export function applyFocus(state,id){const s=clone(state),c=s.countries[s.player];if(c.focuses[id])return s;if(id==='ming_finance_reform'&&c.money>=20){c.money-=20;c.stability=Math.min(100,c.stability+10);c.corruption=Math.max(0,c.corruption-8);c.focuses[id]=true;s.log.unshift('国策完成：财政改革。');}if(id==='ming_military_reform'&&c.money>=25){c.money-=25;c.army+=15000;c.warSupport=Math.min(100,c.warSupport+8);c.focuses[id]=true;s.log.unshift('国策完成：整饬军务。');}return s;}
export function resolveBattle({attackerTroops,defenderTroops,attackerMorale=1,defenderMorale=1,terrain=1}){const a=attackerTroops*attackerMorale*terrain,d=defenderTroops*defenderMorale*(2-terrain*.2);return{winner:a>=d?'attacker':'defender',attackerPower:Math.round(a),defenderPower:Math.round(d)};}
