import {createInitialState,advanceDay,applyFocus,attackProvince} from "./game.mjs";
const $=id=>document.getElementById(id);
const names=["\u5317\u4eac","\u5c71\u897f","\u5c71\u4e1c","\u9655\u897f","\u6cb3\u5357","\u56db\u5ddd","\u6e56\u5e7f","\u6c5f\u82cf","\u5b89\u5fbd","\u6e56\u5357","\u6c5f\u897f","\u6d59\u6c5f","\u798f\u5efa","\u5e7f\u4e1c"],pos=[[72,18],[50,29],[84,34],[34,42],[59,45],[31,60],[52,61],[76,57],[68,52],[50,72],[63,72],[80,72],[82,84],[67,88]],colors={ming:["\u5927\u660e","#b84a42"],shun:["\u5927\u987a","#8d4055"],qing:["\u540e\u91d1","#356f82"]};
let state=JSON.parse(localStorage.getItem("ming-strategy-v03")||"null")||createInitialState();state.provinces=state.provinces||names.map((n,i)=>({id:"p"+i,name:n,x:pos[i][0],y:pos[i][1],owner:"ming",fort:i%3,army:12000}));state.selected=state.selected||state.provinces[0].id;let timer=null;
function persist(){localStorage.setItem("ming-strategy-v03",JSON.stringify(state))}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1600)}
function render(){const c=state.countries[state.player]||{money:100,food:500,army:180000,stability:62,warSupport:55,manpower:280000};$("date").textContent=state.date;$("turn").textContent="第 "+state.turn+" 日";$("resources").innerHTML=[["白银",c.money],["粮食",c.food],["人力",Math.round(c.manpower/1000)+"k"],["军队",Math.round(c.army/1000)+"k"],["稳定",Math.round(c.stability)+"%"],["战意",Math.round(c.warSupport)+"%"]].map(x=>"<div class=stat><span>"+x[0]+"</span><b>"+x[1]+"</b></div>").join("");$("countries").innerHTML=Object.entries(colors).map(([id,v])=>"<button class=country "+(id===state.player?"active":"")+" data-country="+id+"><i style=background:"+v[1]+"></i>"+v[0]+"</button>").join("");$("map").innerHTML=state.provinces.map((p,i)=>"<button class=province "+(p.id===state.selected?"selected":"")+" style=left:"+pos[i][0]+"%;top:"+pos[i][1]+"%;--c:"+colors[p.owner][1]+" data-province="+p.id+"><strong>"+names[i]+"</strong><small>"+colors[p.owner][0]+" · "+Math.round((p.army||0)/1000)+"k</small></button>").join("");const p=state.provinces.find(x=>x.id===state.selected)||state.provinces[0];$("info").innerHTML="<div class=panelTitle>省份情报</div><h2>"+names[state.provinces.indexOf(p)]+"</h2><div class=kv><span>控制者</span><b>"+colors[p.owner][0]+"</b><span>堡垒</span><b>"+p.fort+"</b><span>驻军</span><b>"+Math.round((p.army||0)/1000)+"k</b></div>"+(p.owner!==state.player?"<button class=primary data-action=attack>⚔ 发动进攻</button>":"<div class=hint>己方领土。点击其他省份查看局势。</div>");$("focuses").innerHTML="<div class=focus><div><b>财政改革</b><small>稳定 +10 · 腐败 -8</small></div><button data-focus=ming_finance_reform>20¤</button></div><div class=focus><div><b>整饬军务</b><small>军队 +15k</small></div><button data-focus=ming_military_reform>25¤</button></div>";$("log").innerHTML=(state.log||[]).slice(0,8).map((x,i)=>"<div class=logitem><span>"+String(i+1).padStart(2,"0")+"</span>"+x+"</div>").join("");$("speed").textContent=state.paused?"暂停":state.speed+"×"}
function day(){state=advanceDay(state);persist();render()}
function setSpeed(n){state.speed=n;state.paused=false;clearInterval(timer);timer=setInterval(day,{1:1400,3:500,10:160}[n]);render()}
document.addEventListener("click",e=>{const p=e.target.closest("[data-province]");if(p){state.selected=p.dataset.province;render();return}const c=e.target.closest("[data-country]");if(c){state.player=c.dataset.country;render();return}const f=e.target.closest("[data-focus]");if(f){state=applyFocus(state,f.dataset.focus);persist();render();toast("国策已执行");return}if(e.target.id==="attack"){const r=attackProvince(state,state.selected);if(r.ok){state=r.state;persist();render();toast(state.log[0])}else toast(r.reason);return}const a=e.target.closest("[data-action]");if(a){const r=attackProvince(state,state.selected);if(r.ok){state=r.state;persist();render();toast(state.log[0])}else toast(r.reason);return}if(e.target.id==="next"){day();toast("时间推进一天");return}if(e.target.id==="pause"){state.paused=!state.paused;if(state.paused){clearInterval(timer)}else setSpeed(state.speed||1);render();return}if(e.target.dataset.speed){setSpeed(Number(e.target.dataset.speed));return}if(e.target.id==="save"){persist();toast("存档成功");return}if(e.target.id==="reset"&&confirm("确定重新开始吗？")){localStorage.removeItem("ming-strategy-v03");state=createInitialState();render();toast("新局开始")}});render();

